version: '3.9'

services:

  web:
    build: .
    image: test_api
    command: python manage.py runserver 0.0.0.0:8000
    restart: always
    ports:
      - 8000:8000
    environment:
      - ./.env
    depends_on:
      - db

  celery:
    image: test_api
    command: celery -A api worker -l info  
    volumes:
      - ./logs:/app/logs
    environment:
      - ./.env
    depends_on:
      - web
      - redis

  db:
    container_name: pgdb
    image: postgres:16-alpine
    env_file:
      - ./.env
    restart: always
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  redis:
    image: redis:7.4.0-alpine

  celery-beat:
    image: test_api
    command: celery -A api beat -l INFO
    environment:
      - ./.env
    depends_on:
      - db
      - web
      - redis
      - celery 

  adminer:
    image: adminer
    ports:
      - 8080:8080
    depends_on:
      - db

volumes:
  pg_data: